### ISSUE TITLE
Étude de la documentation et Modélisation dynamique du robot

### ISSUE THREAD

**Issue by thec2511** [thec2511/BARUS#23]

**Comment by williamaris** [comment]
[rigidLinksStresMatlab.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c3f60d2046d060011d67716/125516c66e82c728ace21e0d46fa9d9d2a86afa081e2ac70b04ff5870447337f2806e1673295f127b54778154d555ca9125b0941a8a8db7da5bf6d798e5c0be9d5390e20c43e47bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8a4f3f18041a81fa5c33a28b06.txt)
