### ISSUE TITLE
Dimensionnement Matlab des longueurs du robot

### ISSUE THREAD

**Issue by thec2511** [thec2511/BARUS#36]
Child of #23

**Comment by williamaris** [comment]
[dimensionsMatlab.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c3f60d2046d060011d67716/125516c66e82c728ace21e0d46ec9d97268c90a080e7ac6ea549fc952b046b313916ac217586f76ae5002e025c094bf8100a0947f5a8802fa6b63874de0d5fefd23b4d68d47f40f2ecdd42e64bef62994597b4bd804dc5ec3527e08b8b4d381f07189bb2.txt)

Changer l'extension du fichier .txt -> .m 
Waffle.io ne supportait pas l'extension.
