### ISSUE TITLE
Calcul du couple nécessaire pour soulever un verre

### ISSUE THREAD

**Issue by thec2511** [thec2511/BARUS#6]
Child of #23
Trouver le couple minimal pour soulever un verre remplis de liquide (prendre la densité de l'eau). Garder les variables de longueur établies pour le #4 .

**Comment by boua2842** [comment]
[Calcul du moment.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c3f5f8a98986000103b02fc/125516c66e82c728ace21e0d46cb959620978fe98bfcff4eab50f59a3d046b313916ac217586f76ae5002e025c094bf8100a0947f5a8802fa6b63874de0d5fefd23b4d68d47f40f2ecdd42e64bef62994597b7bb804dc5ec3527e183874b3b1d01199bb2.docx)
